### ISSUE TITLE
Allow to keep not signed extensions as permanent

### ISSUE THREAD

**Issue by charlesmilette** [Noitidart/Chrome-Store-Foxified#25]
That would be useful for users of Firefox Nightly and DevEd, where extensions signing requirement can be disabled with the preference `xpinstall.signatures.required`

**Comment by Noitidart** [comment]
I submitted v2.0 and it features this. After the CRX data is downloaded from the store, it asks you what to do with it. By default it will not sign the addon anymore. You can try it out here please - https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/statistics/usage/versions/

**Comment by charlesmilette** [comment]
I only see that:
![2016-06-08](https://cloud.githubusercontent.com/assets/6440374/15898404/34f7b0ca-2d66-11e6-89b6-7c953712b5d4.png)

**Comment by Noitidart** [comment]
Oh version 2 is under review, you can get it before though from here - https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/versions/

It won't be signed though, so you will have to use on nightly or something with xpisignatures pref set to false.

**Comment by charlesmilette** [comment]
Totally not working:
![gif](https://cloud.githubusercontent.com/assets/6440374/15913818/546afa2c-2daa-11e6-98ed-0fb5981a04c5.gif)

**Comment by Noitidart** [comment]
Oh shoot, thanks for that screencast. I'll look into this right away.

**Comment by Noitidart** [comment]
Oh I figured it out, please try using "English".

I will fix up and release 2.1 to work in non-english langs.

**Comment by charlesmilette** [comment]
English browser or web store?

**Comment by Noitidart** [comment]
Webstore please - ![](http://i.imgur.com/gqT8h5Q.png)

**Comment by charlesmilette** [comment]
Nope:
![2016-06-09](https://cloud.githubusercontent.com/assets/6440374/15929177/6f60586c-2e19-11e6-86c9-8cb74b8ae782.png)

I don't get any console log for `console.log('ariaLabel:', ariaLabel, 'btnText:', btnText);` either.

**Comment by Noitidart** [comment]
Hi there @charlesmilette were you able to get it to work? I can't reproduce this error I tried for a week.

I attached a version which has logging enabled. Can you please:

1. Open browser console with ctrl+shift+j
2. Clear the console.
3. Install this version and paste to me what logs into your console. 
4. Then clear the console
5. Go to chrome store extension page and paste the logs (filter out the security errors as it will be a lot)

How to install:
Please download this zip, then go to about:debugging then "Load temporary addon" and select this zip.

[Chrome-Store-Foxified.zip](https://github.com/Noitidart/Chrome-Store-Foxified/files/319107/Chrome-Store-Foxified.zip)

**Comment by Noitidart** [comment]
Hey @charlesmilette can you please try 2.1 I just uploaded it to the addons.moz it should fix this. Accidentally closed it though, reopening

**Comment by charlesmilette** [comment]
It's working now. But I still can't install an unsigned addon permanently, as it was the reason I opened this issue in the first place.

**Comment by Noitidart** [comment]
Awesome!! Right now you'll have to click "Save unsigned addon", then drag that into firefox. I'll try to get the reviewers to allow it with the reason that the addon may be used in other firefox flavors like waterfox etc. They were pretty staunch about not allowing installation of unsigned addome I tried.

**Comment by trlkly** [comment]
A workaround in the meantime would be to have an unsigned version of your addon that allows people to install unsigned addons. Just host the unsigned version here on Github. 

Still silly of them not to let you. On locked down versions of Firefox, the addon won't actually install if it's unsigned, right? As long as you make sure of that, they should allow it.

**Comment by Noitidart** [comment]
Ah good idea @trlkly I'll knock that up.
