### ISSUE TITLE
Updated issue w/ newest Firefox 

### ISSUE THREAD

**Issue by newsjunkie247** [Noitidart/Chrome-Store-Foxified#31]
In Firefox 50, the button change works and the signing works for this extension (https://chrome.google.com/webstore/detail/buzzsumo/gedpbnanjmblcmlfhgfficjnglidndfo), but then when I try to install it either signed or unsigned I get the message "This add-on could not be installed because it appears to be corrupt" though it works in 45.

**Comment by newsjunkie247** [comment]
(and this one does install, but then doesn't seem to work: https://chrome.google.com/webstore/detail/share-to-facebook/kbgplcfihfeioiaddclapccnefggiddn)

**Comment by Noitidart** [comment]
Thanks for the reports @newsjunkie247 I'll take a look into both. I suspect in the first case, there is a manifest key that is no longer currently supported. And in the second one it might be a lacking API. But I'll investigate. If a key is no longer supported, I'll have foxified remove the key so it doesn't cause issues.

**Comment by Noitidart** [comment]
@newsjunkie247 was your issue resolved with the latest version of Foxified? v2.0 had a lot of fixes.

**Comment by newsjunkie247** [comment]
In the newest nightly versions, (now at 51) I still can't install that add-on, it still says it's corrupt, though I can download and sign. It works in 45. And the addon installed in 45 is not accessible when I open the same profile in 51.

**Comment by Noitidart** [comment]
Found the issue, there is a mistake in this guys addon. When I try to install it says this:

> 1472266747567	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing content_scripts.0.exclude_matches: Array requires at least 1 items; you have 0

You can report to them this bug so they can fix it up. Or you can download it, save the unsigned version, then modify the `manifest.json`, then upload to AMO as unlisted to get it signed.

**Comment by newsjunkie247** [comment]
What should the manifest say? It works fine on FF45 though.

**Comment by Noitidart** [comment]
I didn't look at the manifest, but I'm guessing the user set their first content script like this: `exclude_matches:[]`. So that needs to have an entry. Maybe we should file a bug with bugzilla. It shouldn't error on this, it should just continue.

**Comment by newsjunkie247** [comment]
Yes, that's what it has, but it has the same thing for FF v 45 and there it works. Would you be able to file the Bugzilla error? My tech skills are only very basic.

**Comment by Noitidart** [comment]
Sure thing I'll test it out and do that and let you know. Its a hunch of mine that if i remove that line it will install. If it works then its a bug that 0 length array is causing issues.

**Comment by newsjunkie247** [comment]
thank you. I think it does install when the line is gone but then the add-on doesn't work properly.

**Comment by andreicristianpetcu** [comment]
I'm getting the same error with [this addon](https://my.owndrive.com/index.php/s/OF4PuGOtmRlmcu4/download). I filled a [Bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1313567) for Firefox. It used to work a few days ago in Nightly.

**Comment by Noitidart** [comment]
I think lots of Google Chrome extensions have badly formatted manifest.json - Firefox does not auto fix or ignore for them. I think I'll have to add in the next version of Foxified a way to modify the manifest.json in case of error.

**Comment by andreicristianpetcu** [comment]
@Noitidart Is there a hackish workaround I can use? What should I put in the author field in order for it to work?

**Comment by Noitidart** [comment]
@andreicristianpetcu you would have be (or get familiar) with debugging extensions. I don't know the exact problem but as it install you would have the Browser Console open (Ctrl + Shift + J) and then based on what errors it shows there you would have to tweak the `manifest.json`. The `author` field seems not supported by Mozilla, so we might have to remove that. I'm not sure, it would take some experimenting. I wish I had time to experiment for you but I have so much going on right now. :(

**Comment by andreicristianpetcu** [comment]
Same here with the time :D If I figure something out, I will post it here also.

**Comment by Noitidart** [comment]
Please try v3 - i think this is fixed now - https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
